# Generated by binpac_quickstart

refine flow ENIP_Flow += {
	function proc_enip_message(msg: ENIP_PDU): bool
		%{
		BifEvent::generate_enip_event(connection()->bro_analyzer(), connection()->bro_analyzer()->Conn());
		return true;
		%}
};

refine typeattr ENIP_PDU += &let {
	proc: bool = $context.flow.proc_enip_message(this);
};